spring.application.name=auth-service
server.port=8081

# Database Configuration (PostgreSQL - users_db)
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.oyruegqzmwratxnnyfol
spring.datasource.password=Sumbaranglah
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Java 21 Virtual Threads
spring.threads.virtual.enabled=true

# Custom JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# Internal API Key for service-to-service communication
internal.api.key=${INTERNAL_API_KEY}

# Google SMTP (App Password)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dheafirmasari@gmail.com
spring.mail.password=gcat haja wlsl flhx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


