spring.application.name=audio-service
server.port=8082

# Database Configuration (PostgreSQL - audio_db)
spring.datasource.url=jdbc:postgresql://localhost:5432/audio_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Java 21 Virtual Threads
spring.threads.virtual.enabled=true

# Custom JWT Configuration
jwt.secret=${JWT_SECRET}

# Custom Upload directory path
app.upload.dir=./uploads

#upload size
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Internal Auth service base URL for token validation
auth.service.url=http://localhost:8081

# Internal API Key for service-to-service communication
internal.api.key=${INTERNAL_API_KEY}

